<?php

$composerRequire = [
    "laravel/framework" => "^10.0",
    "laravel/breeze" => "^1.0",
    "laravel/cashier" => "^14.0",
    "laravel/sanctum" => "^3.0",
    "laravel/telescope" => "^4.0",
    "livewire/livewire" => "^3.0",
];

?>
-----
<?php

$composerRequire = [
    "laravel/framework" => '^11.0',
    "laravel/breeze" => '^2.0',
    "laravel/cashier" => '^15.0',
    "laravel/sanctum" => '^4.0',
    "laravel/telescope" => '^5.0',
    "livewire/livewire" => '^3.4',
];

?>
