<?php

$composerRequire = [
    "laravel/framework" => "^12.0",
    "laravel/boost" => "^1.0",
    "laravel/tinker" => "^2.9",
    "phpunit/phpunit" => "^11.0",
    "pestphp/pest" => "^3.0",
];

?>
-----
<?php

$composerRequire = [
    "laravel/framework" => '^13.0',
    "laravel/boost" => '^2.0',
    "laravel/tinker" => '^3.0',
    "phpunit/phpunit" => '^12.0',
    "pestphp/pest" => '^4.0',
];

?>
