<?php

declare(strict_types=1);

namespace MuhammadSadeeq\LaravelUpgradesRector\Upgrade\Rector;

use RuntimeException;

/**
 * Generates the per-run Rector configuration used by the orchestrator
 * (plan P2-06, decision D11): absolute project paths, target set, PHP
 * version, optional Larastan and a project-local cache directory.
 *
 * The generated file is written to .laravel-upgrade/rector-<major>.php so
 * users can inspect and re-run it with plain `vendor/bin/rector`.
 */
final class RectorConfigGenerator
{
    private const PHP_VERSION_CONSTANTS = [
        81 => 'PhpVersion::PHP_81',
        82 => 'PhpVersion::PHP_82',
        83 => 'PhpVersion::PHP_83',
        84 => 'PhpVersion::PHP_84',
    ];

    public function generate(string $projectDirectory, int $targetMajor): string
    {
        $configDirectory = $projectDirectory.'/.laravel-upgrade';

        if (! is_dir($configDirectory) && ! mkdir($configDirectory, 0777, true) && ! is_dir($configDirectory)) {
            throw new RuntimeException(sprintf('Could not create "%s".', $configDirectory));
        }

        $targetPath = $configDirectory.'/rector-'.$targetMajor.'.php';

        $paths = $this->projectPaths($projectDirectory);
        $phpConstant = self::PHP_VERSION_CONSTANTS[$this->phpVersionFor($targetMajor)]
            ?? 'PhpVersion::PHP_82';

        $larastanLine = '';
        $larastan = $projectDirectory.'/vendor/larastan/larastan/extension.neon';

        if (is_file($larastan)) {
            $larastanLine = sprintf("    ->withPHPStanConfigs(['%s'])\n", $larastan);
        }

        $pathLines = implode("\n", array_map(
            static fn (string $path): string => sprintf("        '%s',", $path),
            $paths
        ));

        $contents = <<<PHP
<?php

declare(strict_types=1);

use Rector\\Config\\RectorConfig;
use Rector\\ValueObject\\PhpVersion;
use MuhammadSadeeq\\LaravelUpgradesRector\\Set\\LaravelUpgradeSetList;
use MuhammadSadeeq\\LaravelUpgradesRector\\Rector\\Shared\\ContractSpecLoader;
use MuhammadSadeeq\\LaravelUpgradesRector\\Rector\\Shared\\ImplementMissingInterfaceMethodsRector;

// Generated by laravel-upgrade for the Laravel {$targetMajor} upgrade run.
return RectorConfig::configure()
    ->withSets([
        LaravelUpgradeSetList::LARAVEL_{$targetMajor},
    ])
    ->withConfiguredRule(ImplementMissingInterfaceMethodsRector::class, [
        {$targetMajor},
        ...ContractSpecLoader::forMajor({$targetMajor}),
    ])
    ->withPhpVersion({$phpConstant})
    ->withPaths([
{$pathLines}
    ])
    ->withSkip([
        '{$projectDirectory}/bootstrap/cache',
        '{$projectDirectory}/storage',
        '{$projectDirectory}/vendor',
        '{$projectDirectory}/node_modules',
        '*.blade.php',
    ])//
{$larastanLine}    ->withCache('{$configDirectory}/rector-cache');

PHP;

        if (file_put_contents($targetPath, $contents) === false) {
            throw new RuntimeException(sprintf('Could not write "%s".', $targetPath));
        }

        return $targetPath;
    }

    /**
     * @return list<string>
     */
    private function projectPaths(string $projectDirectory): array
    {
        $paths = [];

        foreach (['app', 'bootstrap', 'config', 'database', 'routes', 'tests'] as $relative) {
            $candidate = $projectDirectory.'/'.$relative;

            if (is_dir($candidate)) {
                $paths[] = $candidate;
            }
        }

        return $paths;
    }

    private function phpVersionFor(int $targetMajor): int
    {
        return match ($targetMajor) {
            13 => 83,
            default => 82,
        };
    }
}
